# whitelist
branches:
  only:
    - master
    - /^tickets\/.*$/

#sudo: required
#
#services:
#    - docker
#
#language: c
#
#before_install:
#    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#    # docker image from public hub are cached by travis
#    - docker pull qserv/mariadb_build:centos
#    # image below won't be cached
#    - docker build -t qserv/mariadb_build:centos tests/centos
#    # push eventual change to cache them for future
#    - docker push qserv/mariadb_build:centos
#    - docker pull qserv/mariadb_build:debian
#    - docker build -t qserv/mariadb_build:debian tests/debian
#    - docker push qserv/mariadb_build:debian
#
#script:
#    - docker run --rm -v $(pwd):/tmp/mariadb qserv/mariadb_build:centos
#    - docker run --rm -v $(pwd):/tmp/mariadb qserv/mariadb_build:debian
#
matrix:
  include:
    - env: TEST=shellcheck
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/*.sh )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        docker run -v $(pwd):$(pwd) -w $(pwd) \
          koalaman/shellcheck-alpine:v0.4.6 -x "${CHECK[@]}"
